# .github/workflows/lint.yml
name: Ruff

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          # run: ruff check --format=github .
          args: check --format=github .
          # optional: tell Ruff what paths to lint (defaults: . and src)
          # src: "."
