# .github/workflows/lint.yml
name: Ruff

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          # Correctly pass the --format argument
          args: check -- --format=github .